import type { Metadata } from "next";
import {Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/Header";
import MarqueePage from "../components/marquee";


const notoSerifBengali = Noto_Serif_Bengali({
  
  subsets: ["latin","bengali"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <HeaderPage/>
        <MarqueePage/>
        {children}
        </body>
    </html>
  );
}
